# Generated by Django 5.1.1 on 2025-01-29 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('biography', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_per_week', models.PositiveIntegerField()),
                ('join_reason', models.TextField(blank=True)),
                ('interesting_ecosystem', models.TextField(blank=True)),
                ('impact_plan', models.TextField(blank=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('expertise', models.CharField(max_length=100)),
                ('experience_years', models.PositiveIntegerField()),
                ('skills', models.TextField(blank=True)),
                ('languages', models.TextField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='members.member')),
            ],
        ),
    ]
