# Generated by Django 5.1.1 on 2025-02-11 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='skill_name',
        ),
    ]
