# Generated by Django 5.1 on 2024-08-26 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='contact_information',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_type',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
