# Generated by Django 5.1.1 on 2025-02-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_skill_skill_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='languages',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skills',
            field=models.TextField(),
        ),
    ]
