# Generated by Django 5.1 on 2024-08-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_remove_member_contact_information_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='hard_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='soft_skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
