# Generated by Django 5.1.1 on 2025-02-23 14:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_skill_languages_alter_skill_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='linkedin_profile',
            field=models.URLField(blank=True, help_text='Enter your LinkedIn profile URL', max_length=255, validators=[django.core.validators.URLValidator()]),
        ),
    ]
