# Generated by Django 5.1 on 2024-09-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_skill_hard_skills_skill_soft_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='impact_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='interesting_ecosystem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='join_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='languages',
            field=models.TextField(blank=True, null=True),
        ),
    ]
