# Generated by Django 5.1.1 on 2025-02-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_linkedin_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='linkedin_profile',
            field=models.URLField(blank=True, max_length=255, verbose_name='LinkedIn Profile'),
        ),
    ]
