# Generated by Django 5.1 on 2024-09-23 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_availability_impact_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='hours_per_week',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='skill',
            name='experience_years',
            field=models.PositiveIntegerField(),
        ),
    ]
