# Generated by Django 5.1.1 on 2025-02-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_member_linkedin_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='discord_handle',
            field=models.CharField(blank=True, help_text='Your Discord username (e.g., username#1234)', max_length=100, null=True),
        ),
    ]
